### ISSUE TITLE
When to call close?

### ISSUE THREAD

**Issue by gitleet** [monix/shade#51]
Hello,

I am using shade in a play application.
I am currently using a singleton for my cache instance:

```
val cache = Memcached(...)
```

Is it ok to use it like this?

And when my application ends, I will then call cache.close?  Is this the best practise?

**Comment by lloydmeta** [comment]
You should definitely call `close()` to cleanup when your Play app shuts down. I think the best way to do it is via `ApplicationLifecycle` (see [the official docs](https://www.playframework.com/documentation/2.5.x/ScalaDependencyInjection#Stopping/cleaning-up))

**Comment by gitleet** [comment]
That is what I am doing, just confirming thanks!
